import yfinance as yf

ticker = yf.Ticker('GOOGL').info
market_price = ticker['regularMarketPrice']
previous_close_price = ticker['regularMarketPreviousClose']
# print(ticker)
print('Ticker: GOOGL')
print('Market Price:', market_price)
print('Previous Close Price:', previous_close_price)

#
# sampledata = {'zip': '94043',
#               'sector': 'Communication Services',
#               'fullTimeEmployees': 186779,
#               'longBusinessSummary': 'Alphabet Inc. provides various products and platforms in the United States, '
#                                      'Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. '
#                                      'It operates through Google Services, Google Cloud, and Other Bets segments. '
#                                      'The Google Services segment offers products and services, including ads, Android, '
#                                      'Chrome, hardware, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, '
#                                      'and YouTube. It is also involved in the sale of apps and in-app purchases and digital '
#                                      'content in the Google Play store; and Fitbit wearable devices, Google Nest home products, '
#                                      'Pixel phones, and other devices, as well as in the provision of YouTube non-advertising services. '
#                                      'The Google Cloud segment offers infrastructure, platform, and other services; Google Workspace '
#                                      'that include cloud-based collaboration tools for enterprises, such as Gmail, Docs, Drive, Calendar, '
#                                      'and Meet; and other services for enterprise customers. The Other Bets segment sells health technology '
#                                      'and internet services. The company was founded in 1998 and is headquartered in Mountain View, California.',
#               'city': 'Mountain View',
#               'phone': '650 253 0000',
#               'state': 'CA',
#               'country': 'United States',
#               'companyOfficers': [],
#               'website': 'https://www.abc.xyz',
#               'maxAge': 1,
#               'address1': '1600 Amphitheatre Parkway',
#               'industry': 'Internet Content & Information',
#               'ebitdaMargins': 0.33225,
#               'profitMargins': 0.23746,
#               'grossMargins': 0.56099,
#               'operatingCashflow': 92814999552,
#               'revenueGrowth': 0.061,
#               'operatingMargins': 0.27849,
#               'ebitda': 93733003264,
#               'targetLowPrice': 93,
#               'recommendationKey': 'buy',
#               'grossProfits': 146698000000,
#               'freeCashflow': 48262373376,
#               'targetMedianPrice': 125,
#               'currentPrice': 92.12,
#               'earningsGrowth': -0.241,
#               'currentRatio': 2.518,
#               'returnOnAssets': 0.13916999,
#               'numberOfAnalystOpinions': 44,
#               'targetMeanPrice': 124.89,
#               'debtToEquity': 11.567,
#               'returnOnEquity': 0.26893,
#               'targetHighPrice': 169.5,
#               'totalCash': 116258996224,
#               'totalDebt': 29336000512,
#               'totalRevenue': 282113015808,
#               'totalCashPerShare': 8.982,
#               'financialCurrency': 'USD',
#               'revenuePerShare': 21.45,
#               'quickRatio': 2.31,
#               'recommendationMean': 1.8,
#               'exchange': 'NMS',
#               'shortName': 'Alphabet Inc.',
#               'longName': 'Alphabet Inc.',
#               'exchangeTimezoneName': 'America/New_York',
#               'exchangeTimezoneShortName': 'EST',
#               'isEsgPopulated': False,
#               'gmtOffSetMilliseconds': '-18000000',
#               'quoteType': 'EQUITY',
#               'symbol': 'GOOGL',
#               'messageBoardId': 'finmb_29096',
#               'market': 'us_market',
#               'annualHoldingsTurnover': None,
#               'enterpriseToRevenue': 3.873,
#               'beta3Year': None,
#               'enterpriseToEbitda': 11.656,
#               '52WeekChange': -0.32263708,
#               'morningStarRiskRating': None,
#               'forwardEps': 5.16,
#               'revenueQuarterlyGrowth': None,
#               'sharesOutstanding': 5973000192,
#               'fundInceptionDate': None,
#               'annualReportExpenseRatio': None,
#               'totalAssets': None,
#               'bookValue': 19.553,
#               'sharesShort': 43102099,
#               'sharesPercentSharesOut': 0.0033000002,
#               'fundFamily': None,
#               'lastFiscalYearEnd': 1640908800,
#               'heldPercentInstitutions': 0.79758,
#               'netIncomeToCommon': 66989998080,
#               'trailingEps': 5.01, 'lastDividendValue': None,
#               'SandP52WeekChange': -0.1262849,
#               'priceToBook': 4.711298,
#               'heldPercentInsiders': 0.07778,
#               'nextFiscalYearEnd': 1672444800,
#               'yield': None,
#               'mostRecentQuarter': 1664496000,
#               'shortRatio': 1.47,
#               'sharesShortPreviousMonthDate': 1669766400,
#               'floatShares': 11260151140,
#               'beta': 1.069061,
#               'enterpriseValue': 1092572610560,
#               'priceHint': 2,
#               'threeYearAverageReturn': None,
#               'lastSplitDate': 1658102400,
#               'lastSplitFactor': '20:1',
#               'legalType': None,
#               'lastDividendDate': None,
#               'morningStarOverallRating': None,
#               'earningsQuarterlyGrowth': -0.265,
#               'priceToSalesTrailing12Months': 4.2433653,
#               'dateShortInterest': 1672358400,
#               'pegRatio': 2.17,
#               'ytdReturn': None,
#               'forwardPE': 17.852715,
#               'lastCapGain': None,
#               'shortPercentOfFloat': 0.0072000003,
#               'sharesShortPriorMonth': 48883523,
#               'impliedSharesOutstanding': 0,
#               'category': None,
#               'fiveYearAverageReturn': None,
#               'previousClose': 91.13,
#               'regularMarketOpen': 90.85,
#               'twoHundredDayAverage': 107.33266,
#               'trailingAnnualDividendYield': 0,
#               'payoutRatio': 0,
#               'volume24Hr': None,
#               'regularMarketDayHigh': 92.19,
#               'navPrice': None,
#               'averageDailyVolume10Day': 29840950,
#               'regularMarketPreviousClose': 91.13,
#               'fiftyDayAverage': 92.4438,
#               'trailingAnnualDividendRate': 0,
#               'open': 90.85, 'toCurrency': None,
#               'averageVolume10days': 29840950,
#               'expireDate': None,
#               'algorithm': None,
#               'dividendRate': None,
#               'exDividendDate': None,
#               'circulatingSupply': None,
#               'startDate': None,
#               'regularMarketDayLow': 90.1299,
#               'currency': 'USD',
#               'trailingPE': 18.387226,
#               'regularMarketVolume': 26329212,
#               'lastMarket': None,
#               'maxSupply': None,
#               'openInterest': None,
#               'marketCap': 1197108625408,
#               'volumeAllCurrencies': None,
#               'strikePrice': None,
#               'averageVolume': 32582769,
#               'dayLow': 90.1299,
#               'ask': 91.93, 'askSize': 800,
#               'volume': 26329212,
#               'fiftyTwoWeekHigh': 151.5465,
#               'fromCurrency': None,
#               'fiveYearAvgDividendYield': None,
#               'fiftyTwoWeekLow': 83.34,
#               'bid': 91.93,
#               'tradeable': False,
#               'dividendYield': None,
#               'bidSize': 1000,
#               'dayHigh': 92.19,
#               'coinMarketCapLink': None,
#               'regularMarketPrice': 92.12,
#               'preMarketPrice': None,
#               'logo_url': 'https://logo.clearbit.com/abc.xyz',
#               'trailingPegRatio': 1.2848
#               }